In [13]:
import backtrader as bt
import backtrader.indicators as btind
import backtrader.feeds as btfeeds
import pandas as pd

In [6]:
# 创建策略
class TestStrategy(bt.Strategy):
    params = (
        #(...,...), # 最后一个“,”最好别删！
    )
    def log(self, txt, dt=None):
        '''可选，构建策略打印日志的函数：可用于打印订单记录或交易记录等'''
        dt = dt or self.datas[0].datetime.date(0)
        print('%s, %s' % (dt.isoformat(), txt))

    def __init__(self):
        '''必选，初始化属性、计算指标等'''
        pass

    def notify_order(self, order):
        '''可选，打印订单信息'''
        pass

    def notify_trade(self, trade):
        '''可选，打印交易信息'''
        pass

    def next(self):
        '''必选，编写交易策略逻辑'''
        sma = btind.SimpleMovingAverage(...) # 计算均线
        pass

In [7]:
cerebro = bt.Cerebro()

In [12]:
data = btfeeds.BacktraderCSVData(backtrader中文教程\Data\trade_info.csv)

SyntaxError: unexpected character after line continuation character (1974225184.py, line 1)

In [16]:
daily_price = pd.read_csv("Data\daily_price.csv", parse_dates=['datetime'])

In [17]:
daily_price

,datetime,sec_code,open,high,low,close,volume,openinterest
0,2019-01-02,600466.SH,33.064891,33.496709,31.954503,32.386321,10629352,0
1,2019-01-02,603228.SH,50.660230,51.458513,50.394136,51.120778,426147,0
2,2019-01-02,600315.SH,148.258423,150.480132,148.258423,149.558935,2138556,0
3,2019-01-02,000750.SZ,49.512579,53.154883,48.715825,51.561375,227557612,0
4,2019-01-02,002588.SZ,36.608672,36.608672,35.669988,35.763857,2841517,0
...,...,...,...,...,...,...,...,...
255967,2021-01-28,600717.SH,121.489201,122.011736,120.705400,120.966667,6022213,0
255968,2021-01-28,300558.SZ,134.155888,137.600704,130.700970,131.569750,5330301,0
255969,2021-01-28,600171.SH,39.774873,39.830040,38.864630,38.947380,12354183,0
255970,2021-01-28,600597.SH,47.190201,49.243025,46.250355,46.423484,32409940,0
255971,2021-01-28,600584.SH,204.725839,210.226650,199.225028,199.799026,68831481,0

In [18]:
trade_info = pd.read_csv("Data/trade_info.csv", parse_dates=['trade_date'])

In [19]:
trade_info

     trade_date   sec_code    weight
0    2019-01-31  000006.SZ  0.007282
1    2019-01-31  000008.SZ  0.009783
2    2019-01-31  000025.SZ  0.006928
3    2019-01-31  000090.SZ  0.007234
4    2019-01-31  000536.SZ  0.003536
...         ...        ...       ...
2490 2021-01-28  603712.SH  0.007630
2491 2021-01-28  603737.SH  0.019291
2492 2021-01-28  603816.SH  0.022646
2493 2021-01-28  603866.SH  0.018611
2494 2021-01-28  688088.SH  0.007600

[2495 rows x 3 columns]

In [20]:
cerebro = bt.Cerebro()

In [22]:
print('Starting Porfolio Value: %.3f' % cerebro.broker.getvalue())

Starting Porfolio Value: 10000.000

In [23]:
print('Final Portfolio Value: %.2f' % cerebro.broker.getvalue())

Final Portfolio Value: 10000.00